SET DATABASE SQL SYNTAX ORA TRUE

drop table SimpleResults if exists;
/

create table SimpleResults (
    id integer generated by default as identity primary key,
    message varchar(80) not null
)
/
